/**
 * Display metadata for Decibel markets: the icon and the human name.
 *
 * Plain data in its own module, with no React or Next imports, so
 * scripts/market-coverage-selftest.ts can read it directly and fail when
 * Decibel lists a market this app has no name or icon for.
 *
 * Icons live in public/tokens. Equity and crypto logos were fetched from
 * Financial Modeling Prep and CoinGecko; COPPER, NATGAS and DRAM have no
 * brand logo and are drawn to match the gold/silver/WTI icons.
 */

export const TOKEN_LOGOS: Record<string, string> = {
  AAVE: "/tokens/aave.svg",
  ADA: "/tokens/ada.svg",
  AMZN: "/tokens/amzn.svg",
  APT: "/tokens/apt.png",
  AVAX: "/tokens/avax.svg",
  BNB: "/tokens/bnb.png",
  BTC: "/tokens/btc.png",
  CBRS: "/tokens/cbrs.svg",
  CHIP: "/tokens/chip.svg",
  DOGE: "/tokens/doge.png",
  ENA: "/tokens/ena.svg",
  ETH: "/tokens/eth.png",
  EWY: "/tokens/ewy.png",
  FARTCOIN: "/tokens/fartcoin.svg",
  GOLD: "/tokens/gold.svg",
  GOOGL: "/tokens/googl.svg",
  HYPE: "/tokens/hype.png",
  KPEPE: "/tokens/kpepe.svg",
  LINK: "/tokens/link.svg",
  MEGA: "/tokens/mega.svg",
  MU: "/tokens/mu.svg",
  NEAR: "/tokens/near.svg",
  NVDA: "/tokens/nvda.svg",
  QQQ: "/tokens/qqq.png",
  SILVER: "/tokens/silver.svg",
  SNDK: "/tokens/sndk.svg",
  SOL: "/tokens/sol.png",
  SPY: "/tokens/spy.png",
  SUI: "/tokens/sui.png",
  TAO: "/tokens/tao.svg",
  TRUMP: "/tokens/trump.svg",
  TSLA: "/tokens/tsla.svg",
  WLFI: "/tokens/wlfi.svg",
  WTIOIL: "/tokens/wtioil.svg",
  XPL: "/tokens/xpl.svg",
  XRP: "/tokens/xrp.png",
  ZEC: "/tokens/zec.png",
  ZRO: "/tokens/zro.svg",
  AAPL: "/tokens/aapl.png",
  AMD: "/tokens/amd.png",
  ARM: "/tokens/arm.png",
  ASML: "/tokens/asml.png",
  BABA: "/tokens/baba.png",
  COIN: "/tokens/coin.png",
  COPPER: "/tokens/copper.svg",
  CRCL: "/tokens/crcl.png",
  DELL: "/tokens/dell.png",
  DRAM: "/tokens/dram.svg",
  HOOD: "/tokens/hood.png",
  IBM: "/tokens/ibm.png",
  INTC: "/tokens/intc.png",
  LIT: "/tokens/lit.png",
  LLY: "/tokens/lly.png",
  META: "/tokens/meta.png",
  MRNA: "/tokens/mrna.png",
  MRVL: "/tokens/mrvl.png",
  MSFT: "/tokens/msft.png",
  MSTR: "/tokens/mstr.png",
  NATGAS: "/tokens/natgas.svg",
  NFLX: "/tokens/nflx.png",
  ORCL: "/tokens/orcl.png",
  PLTR: "/tokens/pltr.png",
  QCOM: "/tokens/qcom.png",
  SAMSUNG: "/tokens/samsung.png",
  SKHYNIX: "/tokens/skhynix.png",
  SPCX: "/tokens/spcx.png",
  TRX: "/tokens/trx.png",
  UBER: "/tokens/uber.png",
  "BTC/USD": "/tokens/btc.png",
  "BTC-PERP/USD": "/tokens/btc.png",
  "ETH/USD": "/tokens/eth.png",
  "SOL/USD": "/tokens/sol.png",
  "APT/USD": "/tokens/apt.png",
  "HYPE/USD": "/tokens/hype.png",
  "BNB/USD": "/tokens/bnb.png",
  "XRP/USD": "/tokens/xrp.png",
  "DOGE/USD": "/tokens/doge.png",
  "SUI/USD": "/tokens/sui.png",
  "ZEC/USD": "/tokens/zec.png",
  "SPY/USD": "/tokens/spy.png",
  "QQQ/USD": "/tokens/qqq.png",
  "EWY/USD": "/tokens/ewy.png",
};

export const MARKET_LABELS: Record<string, string> = {
  AAPL: "Apple",
  ADA: "Cardano",
  AMZN: "Amazon",
  AAVE: "Aave",
  APT: "Aptos",
  BTC: "Bitcoin",
  BNB: "BNB",
  CBRS: "Chainbase",
  CHIP: "Chip",
  DOGE: "Dogecoin",
  ETH: "Ethereum",
  EWY: "iShares MSCI South Korea",
  FARTCOIN: "Fartcoin",
  GOLD: "Gold",
  GOOGL: "Google",
  HYPE: "Hyperliquid",
  KPEPE: "Pepe",
  LINK: "Chainlink",
  MEGA: "Mega",
  MU: "Micron",
  NEAR: "Near",
  NVDA: "Nvidia",
  QQQ: "Invesco QQQ",
  SNDK: "SanDisk",
  SILVER: "Silver",
  SOL: "Solana",
  SPY: "SPDR S&P 500 ETF",
  SUI: "Sui",
  TAO: "Bittensor",
  TRUMP: "Trump",
  TSLA: "Tesla",
  WTIOIL: "WTI Oil",
  XPL: "Plasma",
  XRP: "XRP",
  ZEC: "Zcash",
  ZRO: "LayerZero",
  DRAM: "DRAM Memory",
  LIT: "Lighter",
  AMD: "Advanced Micro Devices",
  ARM: "Arm Holdings",
  ASML: "ASML",
  AVAX: "Avalanche",
  BABA: "Alibaba",
  COIN: "Coinbase",
  COPPER: "Copper",
  CRCL: "Circle",
  DELL: "Dell Technologies",
  HOOD: "Robinhood",
  IBM: "IBM",
  INTC: "Intel",
  LLY: "Eli Lilly",
  META: "Meta Platforms",
  MRNA: "Moderna",
  MRVL: "Marvell",
  MSFT: "Microsoft",
  MSTR: "MicroStrategy",
  NATGAS: "Natural Gas",
  NFLX: "Netflix",
  ORCL: "Oracle",
  PLTR: "Palantir",
  QCOM: "Qualcomm",
  SAMSUNG: "Samsung Electronics",
  SKHYNIX: "SK Hynix",
  SPCX: "SpaceX",
  TRX: "TRON",
  UBER: "Uber",
  WLFI: "World Liberty Financial",
};
